//! Clean-room rename similarity scoring.
//!
//! The rules here were inferred from black-box `git diff --raw -M` observations
//! generated by `cargo xtask rename-score-corpus`, not from Git or libgit2
//! source. Git's emitted score is the floor of copied source bytes as a percent
//! of the larger file. "Copied" bytes are counted by matching content spans:
//! newline-terminated records, with very long records split every 64 bytes.

use rustc_hash::FxHashMap;

/// A blob's span multiset, computed once and reused across every candidate
/// pairing. Mirrors git's signature cache: each file is hashed a single time,
/// not once per comparison, which is what keeps O(adds x deletes) rename
/// detection affordable.
pub(super) struct Signature {
    /// Span bytes -> occurrence count.
    spans: FxHashMap<Box<[u8]>, u32>,
    size: usize,
}

impl Signature {
    pub(super) fn new(bytes: &[u8]) -> Self {
        let mut spans: FxHashMap<Box<[u8]>, u32> = FxHashMap::default();
        for span in Spans::new(bytes) {
            *spans.entry(Box::from(span)).or_default() += 1;
        }
        Self {
            spans,
            size: bytes.len(),
        }
    }

    pub(super) const fn size(&self) -> usize {
        self.size
    }
}

/// Similarity score (0-100) between two precomputed signatures: the floor of
/// copied bytes (spans common to both, weighted by length) as a percent of the
/// larger blob. Non-destructive, so a `Signature` is reusable across pairings.
#[must_use]
pub(super) fn score_sigs(old: &Signature, new: &Signature) -> u8 {
    let max_size = old.size.max(new.size);
    if max_size == 0 {
        return 100;
    }

    // copied = sum over shared spans of min(old_count, new_count) * span_len.
    // Iterate the smaller map and look up in the larger.
    let (small, large) = if old.spans.len() <= new.spans.len() {
        (&old.spans, &new.spans)
    } else {
        (&new.spans, &old.spans)
    };
    let mut copied = 0u64;
    for (span, &count) in small {
        if let Some(&other) = large.get(span) {
            copied += u64::from(count.min(other)) * span.len() as u64;
        }
    }

    // u64 math: on a 32-bit target `copied * 100` would overflow `usize`
    // for a renamed file larger than ~42 MB.
    ((copied * 100) / max_size as u64).min(100) as u8
}

/// Convenience for a single comparison (no signature reuse): builds both
/// signatures, then scores.
#[must_use]
pub(super) fn score(old: &[u8], new: &[u8]) -> u8 {
    score_sigs(&Signature::new(old), &Signature::new(new))
}

struct Spans<'a> {
    bytes: &'a [u8],
}

impl<'a> Spans<'a> {
    const MAX_LEN: usize = 64;

    const fn new(bytes: &'a [u8]) -> Self {
        Self { bytes }
    }
}

impl<'a> Iterator for Spans<'a> {
    type Item = &'a [u8];

    fn next(&mut self) -> Option<Self::Item> {
        if self.bytes.is_empty() {
            return None;
        }

        let newline_len = self
            .bytes
            .iter()
            .position(|&b| b == b'\n')
            .map_or(self.bytes.len(), |idx| idx + 1);
        let span_len = newline_len.min(Self::MAX_LEN);
        let (span, rest) = self.bytes.split_at(span_len);
        self.bytes = rest;
        Some(span)
    }
}

#[cfg(test)]
mod tests {
    use super::score;

    fn numbered_lines(prefix: &str, count: usize) -> Vec<u8> {
        let mut bytes = Vec::new();
        for i in 0..count {
            bytes.extend_from_slice(format!("{prefix}-{i:02}\n").as_bytes());
        }
        bytes
    }

    #[test]
    fn scores_exact_and_empty_renames() {
        assert_eq!(score(b"", b""), 100);
        assert_eq!(score(b"one", b"one"), 100);
        assert_eq!(score(b"one", b"two"), 0);
    }

    #[test]
    fn scores_line_changes_by_copied_bytes_over_larger_file() {
        let old = numbered_lines("line", 20);
        let mut new = numbered_lines("line", 18);
        new.extend_from_slice(b"changed-18\nchanged-19\n");

        assert_eq!(score(&old, &new), 86);
    }

    #[test]
    fn scores_reordered_lines_as_copied() {
        let old = numbered_lines("line", 20);
        let mut new = Vec::new();
        new.extend_from_slice(&old[80..]);
        new.extend_from_slice(&old[..80]);

        assert_eq!(score(&old, &new), 100);
    }

    #[test]
    fn splits_long_records_at_sixty_four_bytes() {
        let old = vec![b'a'; 4096];
        let mut new = old.clone();
        new[2048] = b'b';

        assert_eq!(score(&old, &new), 98);
    }

    #[test]
    fn newline_boundaries_cap_binary_like_records() {
        let old: Vec<u8> = (0u8..=255).map(|i| i.wrapping_mul(17)).collect();
        let mut new = old.clone();
        new[100] ^= 0xff;

        assert_eq!(score(&old, &new), 83);
    }
}
