//! Clean-room rename similarity scoring.
//!
//! The rules here were inferred from black-box `git diff --raw -M` observations
//! generated by `cargo xtask rename-score-corpus`, not from Git or libgit2
//! source. Git's emitted score is the floor of copied source bytes as a percent
//! of the larger file. "Copied" bytes are counted by matching content spans:
//! newline-terminated records, with very long records split every 64 bytes.

use std::hash::{Hash as _, Hasher as _};

use rustc_hash::{FxHashMap, FxHasher};

/// A blob's span multiset, computed once and reused across every candidate
/// pairing (git's signature cache: each file is hashed once, not once per
/// comparison, which keeps O(adds x deletes) rename detection affordable).
///
/// Spans are keyed by `(hash, byte length)` rather than their raw bytes, so
/// neither building the signature nor probing it allocates or re-hashes span
/// bytes in the hot path. The 64-bit span hash makes collisions far rarer than
/// git's own (git hashes spans to 32 bits), so scores stay identical to a
/// byte-exact comparison in practice.
pub(super) struct Signature {
    spans: FxHashMap<(u64, u32), u32>,
    size: usize,
}

impl Signature {
    pub(super) fn new(bytes: &[u8]) -> Self {
        let mut spans: FxHashMap<(u64, u32), u32> = FxHashMap::default();
        for span in Spans::new(bytes) {
            *spans
                .entry((hash_span(span), span.len() as u32))
                .or_default() += 1;
        }
        Self {
            spans,
            size: bytes.len(),
        }
    }

    pub(super) const fn size(&self) -> usize {
        self.size
    }
}

fn hash_span(span: &[u8]) -> u64 {
    let mut hasher = FxHasher::default();
    span.hash(&mut hasher);
    hasher.finish()
}

/// A rename similarity, kept as the exact ratio `copied / max_size` rather than a
/// rounded percent. git orders rename candidates by this fine score (two pairs
/// that both display `R83` are not a tie to git unless their ratios are exactly
/// equal), so [`Ord`] compares the unrounded ratio; [`Self::percent`] is only for
/// the displayed `R{n}`.
#[derive(Clone, Copy)]
pub(super) struct Similarity {
    copied: u64,
    max_size: u64,
}

impl Similarity {
    /// An exact (same-blob) rename: ratio 1.0, percent 100.
    pub(super) const EXACT: Self = Self {
        copied: 1,
        max_size: 1,
    };

    /// The displayed percent (`R{n}`): floor of `copied * 100 / max_size`, capped
    /// at 100. Matches git's reported similarity index.
    #[must_use]
    pub(super) fn percent(self) -> u8 {
        if self.max_size == 0 {
            return 100;
        }
        ((self.copied * 100) / self.max_size).min(100) as u8
    }
}

impl PartialEq for Similarity {
    fn eq(&self, other: &Self) -> bool {
        self.cmp(other) == std::cmp::Ordering::Equal
    }
}
impl Eq for Similarity {}
impl PartialOrd for Similarity {
    fn partial_cmp(&self, other: &Self) -> Option<std::cmp::Ordering> {
        Some(self.cmp(other))
    }
}
impl Ord for Similarity {
    fn cmp(&self, other: &Self) -> std::cmp::Ordering {
        // copied/max vs other.copied/other.max, cross-multiplied (u128, exact).
        (u128::from(self.copied) * u128::from(other.max_size))
            .cmp(&(u128::from(other.copied) * u128::from(self.max_size)))
    }
}

/// Similarity between two precomputed signatures: copied bytes (spans common to
/// both, weighted by length) over the larger blob. Non-destructive, so a
/// `Signature` is reusable across pairings.
#[must_use]
pub(super) fn score_sigs(old: &Signature, new: &Signature) -> Similarity {
    let max_size = (old.size.max(new.size)) as u64;
    if max_size == 0 {
        return Similarity::EXACT;
    }

    // copied = sum over spans in both of min(old_count, new_count) * span_len.
    // Iterate the smaller map and probe the larger by the `(hash, len)` key.
    let (small, large) = if old.spans.len() <= new.spans.len() {
        (&old.spans, &new.spans)
    } else {
        (&new.spans, &old.spans)
    };
    let mut copied = 0u64;
    for (key, &count) in small {
        if let Some(&other) = large.get(key) {
            copied += u64::from(count.min(other)) * u64::from(key.1);
        }
    }

    Similarity { copied, max_size }
}

/// Convenience for a single comparison (no signature reuse): builds both
/// signatures, then returns the displayed percent.
#[must_use]
pub(super) fn score(old: &[u8], new: &[u8]) -> u8 {
    score_sigs(&Signature::new(old), &Signature::new(new)).percent()
}

/// For every deletion, the [`Similarity`] to each addition that shares at least
/// one span - the only additions that can score above zero. An inverted index
/// over the additions' spans turns the `deletions x additions` matrix git walks
/// in full into work proportional to the *overlapping* pairs, so a status whose
/// renames don't all share content (the usual case) costs far less. Returns
/// `(deletion index, addition index, similarity)`; `None` signatures (unreadable
/// blobs) contribute nothing.
#[must_use]
pub(super) fn overlapping_pairs(
    deletions: &[Option<Signature>],
    additions: &[Option<Signature>],
) -> Vec<(usize, usize, Similarity)> {
    // Inverted index: span (hash, len) -> additions containing it, with count.
    let mut index: FxHashMap<(u64, u32), Vec<(usize, u32)>> = FxHashMap::default();
    for (add_idx, sig) in additions.iter().enumerate() {
        if let Some(sig) = sig {
            for (&key, &count) in &sig.spans {
                index.entry(key).or_default().push((add_idx, count));
            }
        }
    }

    let mut pairs = Vec::new();
    // `copied[add_idx]` accumulates shared bytes for the current deletion; only
    // the touched entries are reset between deletions, so sparse cases stay cheap.
    let mut copied = vec![0u64; additions.len()];
    let mut touched: Vec<usize> = Vec::new();
    for (del_idx, sig) in deletions.iter().enumerate() {
        let Some(del_sig) = sig else { continue };
        for (key, &del_count) in &del_sig.spans {
            let Some(postings) = index.get(key) else {
                continue;
            };
            let len = u64::from(key.1);
            for &(add_idx, add_count) in postings {
                if copied[add_idx] == 0 {
                    touched.push(add_idx);
                }
                copied[add_idx] += u64::from(del_count.min(add_count)) * len;
            }
        }
        for &add_idx in &touched {
            let add_size = additions[add_idx].as_ref().map_or(0, Signature::size);
            pairs.push((
                del_idx,
                add_idx,
                Similarity {
                    copied: copied[add_idx],
                    max_size: del_sig.size.max(add_size) as u64,
                },
            ));
            copied[add_idx] = 0;
        }
        touched.clear();
    }
    pairs
}

struct Spans<'a> {
    bytes: &'a [u8],
}

impl<'a> Spans<'a> {
    const MAX_LEN: usize = 64;

    const fn new(bytes: &'a [u8]) -> Self {
        Self { bytes }
    }
}

impl<'a> Iterator for Spans<'a> {
    type Item = &'a [u8];

    fn next(&mut self) -> Option<Self::Item> {
        if self.bytes.is_empty() {
            return None;
        }

        let newline_len = self
            .bytes
            .iter()
            .position(|&b| b == b'\n')
            .map_or(self.bytes.len(), |idx| idx + 1);
        let span_len = newline_len.min(Self::MAX_LEN);
        let (span, rest) = self.bytes.split_at(span_len);
        self.bytes = rest;
        Some(span)
    }
}

#[cfg(test)]
mod tests {
    use super::score;

    fn numbered_lines(prefix: &str, count: usize) -> Vec<u8> {
        let mut bytes = Vec::new();
        for i in 0..count {
            bytes.extend_from_slice(format!("{prefix}-{i:02}\n").as_bytes());
        }
        bytes
    }

    #[test]
    fn scores_exact_and_empty_renames() {
        assert_eq!(score(b"", b""), 100);
        assert_eq!(score(b"one", b"one"), 100);
        assert_eq!(score(b"one", b"two"), 0);
    }

    #[test]
    fn scores_line_changes_by_copied_bytes_over_larger_file() {
        let old = numbered_lines("line", 20);
        let mut new = numbered_lines("line", 18);
        new.extend_from_slice(b"changed-18\nchanged-19\n");

        assert_eq!(score(&old, &new), 86);
    }

    #[test]
    fn scores_reordered_lines_as_copied() {
        let old = numbered_lines("line", 20);
        let mut new = Vec::new();
        new.extend_from_slice(&old[80..]);
        new.extend_from_slice(&old[..80]);

        assert_eq!(score(&old, &new), 100);
    }

    #[test]
    fn splits_long_records_at_sixty_four_bytes() {
        let old = vec![b'a'; 4096];
        let mut new = old.clone();
        new[2048] = b'b';

        assert_eq!(score(&old, &new), 98);
    }

    #[test]
    fn newline_boundaries_cap_binary_like_records() {
        let old: Vec<u8> = (0u8..=255).map(|i| i.wrapping_mul(17)).collect();
        let mut new = old.clone();
        new[100] ^= 0xff;

        assert_eq!(score(&old, &new), 83);
    }
}
